### ISSUE TITLE
Clarify Licensing CC-BY  vs CC-BY-SA

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/glossary#100]
The license after the front page is stated as CC-BY-SA, on page 3 it is declared CC-BY.

**Comment by gernotstarke** [comment]
you have all required access rights to commit/push a fix :-)

**Comment by alxlo** [comment]
I will gladly do that. But which license should it be?

**Comment by gernotstarke** [comment]
I don't really  care...  The differences don't seem important to me...



Dr. Gernot Starke
+49-177-7282570
gs@gernotstarke.de
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.

**Comment by alxlo** [comment]
The Share-Alike comes from the generation process of the Leanpub Edition. I changed this from CC-BY-SA to CC-BY to match the license given in the repository.
