### ISSUE TITLE
orphan footnote

### ISSUE THREAD

**Issue by WolfgangFahl** [isaqb-org/glossary#120]
This was in the wrong md file - i assume it should go to term-DDD.md but don't know how the footnote principle is fixed.

³⁵<http://dddcommunity.org/learning-ddd/what_is_ddd/>

**Comment by gernotstarke** [comment]
@WolfgangFahl on one hand I really appreciate your plentiful commits, on the other hand we follow a pretty strict 4-eye principle on pushes to production branches over most repos at iSAQB

Within the FLWG we decided to protect the main/master branch, and I simply forgot to enable this rule in the glossary repo.

I did that right now, therefore pushing is ONLY allowed after a second person approves any pull request.
Please open feature branches and create PRs if you want content to be merged. You may well collect any number of smaller changes into one PR. Larger changes (e.g. updates to term definitions or new terms) should get their own branch.

You could assign the PR to e.g. @programming-wolf @mikesperber @alxlo @p-goetz @rhoadesre  or @gernotstarke, we are all willing to support the active development and improvement of the glossary.

On Nov 11th we will start converting the existing content to the ascidoc based toolchain - that has been decided by a FLWG group meeting last week. As you told in a comment, that doesn't pose any problem for you.

 I initially write this in an issue comment, but will try to send it as an email later on.
regards
Gernot

**Comment by WolfgangFahl** [comment]
@gernotstarke  i am fine with this, especially since i am starting to do actual content work now such as translating items. If we switch on google discussions we might be able to simplify the process.

**Comment by gernotstarke** [comment]
I converted DDD.md to DDD.adoc, and there is no footnote. Issue resolved.
