### ISSUE TITLE
get rid of categories - as they don't provide additional value

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/glossary#149]
We did never really use categories, so we should eliminate them altogether.

**Comment by ichsteffen** [comment]
Are you really sure?

**Comment by gernotstarke** [comment]
yes, I'm really sure. 

Originally we wanted to generate category-specific tables - but actually nobody ever asked for such a feature, and nobody wanted to implement it. 
So what is the information good for? Just takes up space. Haven't been maintained properly (Kategorie vs Category, not used uniformely).

Not all terms had categories. Some had many. 

There's already a PR for it. More than 150 lines deleted :-)

**Comment by WolfgangFahl** [comment]
Currently the categories are the  only way that the glossary can be filtered. E.g the security and quality attribute entries are currently iMHO a bit "bloated" if we have glossary entries per curriculum things get more interesting. IMHO we definetly need a tag or category  approach (but not necessarily both).

**Comment by gernotstarke** [comment]
in principle, I'm with you.

in case of our glossary and its (former) categories: They were a  huge mess - and any filtering would imho have provided partial or misleading information.

Second point: What is the usecase for filtering the glossary? Who benefits from such a filter? Imho none and nobody.
Let's invest more energy in providing good explanations and definitions, and less energy in formal stuff.

**Comment by WolfgangFahl** [comment]
Please rethink this and wait until more people have given their comment. My partner companies would probably love to have a say. I'll get back to this after talking to e.g. Bert-Jan.

**Comment by gernotstarke** [comment]
In case you want to analyze, filter or otherwise modify, I suggest you fork this repo.

I will not accept arbitrary comments or opinions (may these origin in your partner companies or elsewhere). Based upon the weight of contributions (https://github.com/isaqb-org/glossary/graphs/contributors) I think I somewhat deserved the right to decide certain aspects - and at least a few other contributors favored my decision.

**Comment by mikesperber** [comment]
What @WolfgangFahl wants is good and desirable, but what he have/had in the glossary just isn't that. Only a few entries have it, there's no taxonomy design etc. Doing all of that would be a worthwhile issue.
