### ISSUE TITLE
Introduce "categories" (or tags)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/glossary#16]
To give more structure to the terms, add categories, for example:
- design-principle
- design-pattern
- architecture-pattern
- ddd (for advanced-level module)
- improve (for advanced-level module "improve")
-  foundation
- advanced (generic for CPSA-Advanced modules)
  - advanced-improve
  - advanced-ddd
- advanced...
- ...

**Comment by gernotstarke** [comment]
* foundation
* advanced-improve
* advanced-ddd

**Comment by gernotstarke** [comment]
@AndreasRausch has promised to review these and add further categories (by end of July 2016)

**Comment by gernotstarke** [comment]
We have to decide upon a technical means of working with these categories (@AndreasRausch... please help here):

The easiest way would be appending

"Categories: xxxx,xxxx" immediately after the term heading, e.g.

##### Adapter
Category: Design-pattern, Foundation

**Comment by gernotstarke** [comment]
Next task would be to generate category-lists from the category-entries... and include them in the book... that would require (lenient) markdown parsing - see #62.

**Comment by programming-wolf** [comment]
Currently, there are no categories anymore. Should we need them, we will start on a green field.
