### ISSUE TITLE
Improve Structure Creation

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/glossary#164]
Currently, all letters are created as heading in the glossary, even if there are no entries. It would be nice to have only the letters added that actually feature entries. 🙂 

Do you want to have a look, @ichsteffen ?

**Comment by gernotstarke** [comment]
we could fix this manually by removing those letters that have no entries...

**Comment by ichsteffen** [comment]
Should be not a big issue. I can do this next week. 
At the moment I do not have access to any workstation. Sorry for the delay.

**Comment by programming-wolf** [comment]
Fixed with #190
