### ISSUE TITLE
fix "my personal opinion"

### ISSUE THREAD

**Issue by mattes3** [isaqb-org/glossary#18]
Term "round trip engineering":

> In my personal opinion, it does not work in practical situations, only in hello-world-like scenarios.

As the book has multiple authors, it should be made clear whose opinion it is. (A few years ago, I was of the same opinion. Recently I have seen code that originated from DDD where reverse engineering did indeed work).

**Comment by Hruschka** [comment]
A glossary should never ever have personal opinions. Therefore, no need to make clear who wrote a definition.

**Comment by gernotstarke** [comment]
imho better to:

1. give clear references, wherever appropriate
2. provide alternatives where that seems appropriate.

**Comment by gernotstarke** [comment]
Additional idea: Explicitely allow comments from single authors, e.g. with subsections like this:

###### Comment (Gernot Starke)
In my personal opinion, it does not work in practical situations, only in hello-world-like scenarios.
###### Comment (Matthias Bohlen)
Recently I have seen code that originated from DDD where reverse engineering did indeed work.

**Comment by gernotstarke** [comment]
Will try this with "Discussion asides", prefixed by "D>"

**Comment by gernotstarke** [comment]
Looks good, will close this and allow personal opinions in these asides. 
Added this to readme.md
