### ISSUE TITLE
Correct references to Kanban

### ISSUE THREAD

**Issue by MichaelMahlberg** [isaqb-org/glossary#29]
Kanban is _not_ an agile method that requires an iterative incremental approach – it is a process optimization method wich _can_ be used in iterative and incremental approachess.

**Comment by MichaelMahlberg** [comment]
Shouldn't this one be "done" or "closed" after the merge?

**Comment by gernotstarke** [comment]
@MichaelMahlberg : move it to done if you think it's ok now... You're the expert :-)

**Comment by gernotstarke** [comment]
@MichaelMahlberg - what's the status? If bug is fixed, just close it ...

**Comment by MichaelMahlberg** [comment]
Definitely closed for quite a while now – I just don't understand (yet) why the commit didn't trigger the close automatically. 
Closing it now via the UI (I hope)

**Comment by gernotstarke** [comment]
thaaaat was fast :-) thanx
