### ISSUE TITLE
Warning sign on Michael's bio

### ISSUE THREAD

**Issue by MichaelMahlberg** [isaqb-org/glossary#46]
Hello everybody – there is a strange warning caused by my latest edits which I can't really understand.

![warningbiomm](https://cloud.githubusercontent.com/assets/119759/16544804/7a549be0-4113-11e6-968f-c97ff3d69e8d.png)

Do you have any pointers on what might have gone wrong? Or where I could find warning messages from the lean-pub build?

**Comment by gernotstarke** [comment]
without looking at the sources: I bet it's a missing image... (you have copied the text... and the others included their companies logo...)... Give me a minute to fix :-)

**Comment by gernotstarke** [comment]
bad guess... it's Mahbouba's image, that is missing or incorrectly... renamed her photo...and added a line of text.
