### ISSUE TITLE
implement category-list generator

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/glossary#62]
We want category-lists, automatically generated from the markdown source of the book.
- parse markdown for "Category: X,Y..." entries (lenient parsing...)
- create lists for every category (under common level-1 heading)

**Comment by WolfgangFahl** [comment]
could you please be a bit more specific about the categories?

**Comment by programming-wolf** [comment]
Since we removed the categories from the glossary altogether, can we close this issue? Should we want to re-introduce categories, we should gather requirements first, check everything we need, and then create issues for that.

**Comment by gernotstarke** [comment]
yes, good point. We close this.
