### ISSUE TITLE
translate ALL terms

### ISSUE THREAD

**Issue by AndreasRausch** [isaqb-org/glossary#68]
There might be a special reson, for instance, that the translations are well-known, however it would
also be nice for readers to have the complete list of terms in the translation table...

**Comment by gernotstarke** [comment]
you're serious about such trivial terms? We have a similar issue with "Documentation"... I have no real stakes in this... If you like, just add them...

**Comment by AndreasRausch** [comment]
Well, as a (new) reader, I would had expected to have all in the glossary defined terms in the translation section. I (personaly) would not expect to have a selction of the existing list of terms in the translation tables...

However, that's just my personal view of what i would have expected....there might be other "reader types"... :-)

**Comment by gernotstarke** [comment]
all right - let's add this issue (and add more translations).

I need to rename the title of this issue...

**Comment by gernotstarke** [comment]
original title was: "Term architecture and term software architecture is not list of translations..."
