### ISSUE TITLE
Architectural Decision

### ISSUE THREAD

**Issue by AndreasRausch** [isaqb-org/glossary#76]
https://leanpub.com/isaqbglossary/read#ArchitecturalDecision

"Architectural Decision
Decision, which has an sustainable or essential effect **on structures, concepts, implementations or similar**. Example: Decision about database technology or technical basics of the user interface."

change to

"Architectural Decision
Decision, which has an sustainable or essential effect **on the architecture**. Example: Decision about database technology or technical basics of the user interface."

BTW: This is a general issue. We should double check and avoid multiple definitions. (Single Responsibility Principle :-), we need an architecture of the glossary :-))

**Comment by gernotstarke** [comment]
+1 for the change-of-wording, that's ok.

**Comment by gernotstarke** [comment]
the "principles" are not always clearly defined resp. separated in publications...  SRP and Separation-of-Concern imho is nearly the same thing, but nevertheless I strive for keeping both.
