### ISSUE TITLE
Architectural Goal

### ISSUE THREAD

**Issue by AndreasRausch** [isaqb-org/glossary#79]
https://leanpub.com/isaqbglossary/read#ArchitecturalGoal

"Architecture goal

(syn: **quality goal, quality requirement**): A quality attribute that the system need to achieve. These goals often have long term character in contrast to (short term) project goals."

Change to:
"Architecture goal

(syn: **Architectural quality goal, Architectural quality requirement**): A quality attribute that the system need to achieve **and the quality attribute is assigned to be architectural issue. Hence, the architecture is resp. has to be designed to fullfill this architectural goal.** These goals often have long term character in contrast to (short term) project goals."

**
- Moreover: Should "syn" be links / references to the corresponding terms?

**

**Comment by gernotstarke** [comment]
+1, well said.

**Comment by gernotstarke** [comment]
added references from "Architecture quality goal" and "Architecture quality requirement" back to architecture goal.
