### ISSUE TITLE
ATAM

### ISSUE THREAD

**Issue by AndreasRausch** [isaqb-org/glossary#81]
https://leanpub.com/isaqbglossary/read#ATAM

From my point of view, it's not worth to add an extra Glossary for ATAM. 

What we should add is the term of "Architectural Analysis Methods". And ATAM is one (obviously the most well-known) example of an architectural analysis method. But there are a bunch  of others: BTAM, CTAM, etc.

**Comment by gernotstarke** [comment]
ATAM is explicitly mentioned in CPSA-F learning goals, and there are examination questions related specifically to ATAM. Therefore, we need an explanation in the glossary.

Second - it's imho also the only widely-applied analysis method :-)

**Comment by gernotstarke** [comment]
closed - all terms and abbreviations from examination questions should be contained in the glossary.
