### ISSUE TITLE
add "slugs" for all patterns mentioned in CPSA-F curriculum v4

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/glossary#82]
numerous patterns of R1 and R3 relevance need an entry in the glossary!!

A brief description ("slug"), best with an (online) reference 

#### Sub Tasks

In order of appearance in LG2-5

- [x] Layers (R1)
- [ ] Pipes-and-Filter (R1)
- [x] Microservices (R1)
- [x] Dependency Injection (R1)
- [ ] Blackboard
- [x] Broker
- [ ] Combinator
- [ ] CQRS (Command-Query-Responsibility-Segregation)
- [ ] Event-Sourcing
- [ ] Interpreter
- [x] MVC (Model View Controller)
- [ ] MVVM (Model View ViewModel)
- [ ] MVU (Model View Update)
- [ ] PAC (Presentation Abstraction Control)
- [x] Adapter
- [x] Facade
- [x] Proxy
- [x] Observer
- [ ] Plug-In
- [ ] Ports&Adapters
- [ ] Onion-Architecture
- [ ] Hexagonal-Architecture
- [ ] Clean-Architecture)
- [ ] Remote Procedure Cal
- [ ] SOA (Service-Oriented Architecture)
- [ ] Template and Strategy
- [ ] Visitor

**Comment by gernotstarke** [comment]
I took the freedom to assign a few contributors... Wolfgang and Mike, 3+ contributions will make you authors on Leanpub...

**Comment by programming-wolf** [comment]
Is this still relevant?

**Comment by alxlo** [comment]
I've added a list of all the patterns that might profit from a reference. Currently open are:

- Pipes-and-Filter (R1)
- Blackboard
- Combinator
- CQRS (Command-Query-Responsibility-Segregation)
- Event-Sourcing
- Interpreter
- MVVM (Model View ViewModel)
- MVU (Model View Update)
- PAC (Presentation Abstraction Control)
- Plug-In
- Ports&Adapters
- Onion-Architecture
- Hexagonal-Architecture
- Clean-Architecture)
- Remote Procedure Cal
- SOA (Service-Oriented Architecture)
- Template and Strategy
- Visitor

**Comment by skogsbaer** [comment]
#199 adds all patterns mentioned in [the very first comment of this issue](https://github.com/isaqb-org/glossary/issues/82#issue-213521221)
