### ISSUE TITLE
Aspects and correlations of (embedded) SW architecture in a mind-map

### ISSUE THREAD

**Issue by dirkengel** [isaqb-org/glossary#86]
Hi,
I created a mind-map about aspects and correlations of (embedded) SW architecture. A one-pager that gives an overall overview in order to explain people what software architecture is all about. Well, the current result is an already very full page and far from being complete (it never will/can be), but maybe it is useful for the glossary nevertheless:
[DEngel_SoftwareArchitectureMindMap_20190126.pdf](https://github.com/isaqb-org/glossary/files/2805058/DEngel_SoftwareArchitectureMindMap_20190126.pdf)
Regards,
Dirk Engel

P.S. this one is a newer version of a mind-map initially shared via https://www.linkedin.com/feed/update/urn:li:activity:6492442092210520065/

**Comment by gernotstarke** [comment]
wont fix - imho the mindmap is too complicated to include in a book or pdf
