### ISSUE TITLE
Package Principles

### ISSUE THREAD

**Issue by flowtoolz** [isaqb-org/glossary#89]
Thanks for compiling this book. It surely is helpful in getting a grasp on the consensus terminology of the industry. 

First thing I noticed was the lack of Robert Martin's six Package Principles:
https://en.wikipedia.org/wiki/Package_principles

He recently re-iterated the package principles in the "[Clean Architecture](https://www.goodreads.com/book/show/18043011-clean-architecture)" book.

Are they just not included yet or is there a reason for why they were left out?

**Comment by rhoadesre** [comment]
Hello,

thanks for the information. We create the book in our spare time so that it sometimes takes a while to include the things that we want. I’ll add this to the list of ToDos.

Best regards,

Roger E. Rhoades

[00 Albion Logo with Slogan - Medium]

Trainer & Owner
+49 152 53 44 33 55
r.rhoades@albion.eu<mailto:r.rhoades@albion.eu>
www.albion.eu<http://www.albion.eu/>

**Comment by flowtoolz** [comment]
Hello @rhoadesre,

Thanks for your quick response.
I'm just pleased there's no professional reservation against including them.

If it might help in including them quicker, I can offer drafts, references and german translation suggestions. I suppose there'll be 6 articles for the principles and one as a summary.

I suggest one aspect will require careful commenting: How Martin's "package" term relates to terms established in the glossary, and related to that, the range of artifacts (architectural elements) to which the package principles reasonably apply.

Kind regards,
Sebastian

**Comment by rhoadesre** [comment]
Hi Sebastian,
it sounds like you're a better man than me to update the glossary. I'll see if it's possible for you to update it directly.
Regards,
Roger

**Comment by gernotstarke** [comment]
Sebastian,
the easiest way for updating would be a Pull Request.

But: A slight downside of including these principles is (currently!) that they are not part of any iSAQB curriculum (but it'd be interesting to have them replace the currently mentioned SOLID principles...)

But imho it's perfectly ok to include them anyway... looking forward to your PR

**Comment by flowtoolz** [comment]
Danke! Bis Sonntag sollte ich es schaffen.

> but it'd be interesting to have them replace the currently mentioned SOLID principles...
Ja, da gibt es Überschneidungen. So weit ich es verstehe sind die Package Principles jedoch durchaus als Ergänzung gedacht. Meiner Ansicht nach ist es auch an der Zeit die 11 Prinzipien neu zu durchdenken und zu integrieren. Das ADP etwa gilt nicht nur für "Packages" (siehe https://www.langlebige-softwarearchitekturen.de). Aber diesen Beitrag zu leisten ist wohl nicht Sinn eines Glossars und auch noch etwas "above my paygrade" :)

**Comment by gernotstarke** [comment]
keine Eile - ich bin aktuell (mal wieder) so landunter, dass ich sowieso die nächsten 2-3 Wochen nicht zu einem Review komme... lass' Dir Zeit!!

**Comment by flowtoolz** [comment]
[Hier ist der Pull Request](https://github.com/isaqb-org/glossary/pull/90).

**Comment by alxlo** [comment]
Package Principles have been added with merge of [Pull Request #90](https://github.com/isaqb-org/glossary/pull/90).

I think it's OK to close this issue.
