### ISSUE TITLE
fix bad link to iso25000.com

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/glossary#91]
that's an scam advertising website, and NOT the official ISO standards page.

I'm afraid we should fix all references to this url...

**Comment by alxlo** [comment]
We _could_ fix this by linking to https://www.iso.org/standard/35733.html but the genuine ISO site provides less information.

**Comment by rhoadesre** [comment]
+1

**Comment by gernotstarke** [comment]
but better any official source than a potentially misleading inofficial one. They don't provide an imprint, and we don't know who are the authors...

**Comment by alxlo** [comment]
I think the preview of ISO25010 has quite some value as it contains at least the definition of quality attributes for free.
https://www.iso.org/obp/ui/#iso:std:iso-iec:25010:ed-1:v1:en

**Comment by gernotstarke** [comment]
sorry for adding the duplicate #180, I did not find this (#91) in the project kanban view, for whatever reason...
