### ISSUE TITLE
There are more meanings to "interface"

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/glossary#98]
The current definition "Boundary across which two building blocks interact or communicate with each other." just does not cut it. 

 ISO/IEC/IEEE 24765:2017(E) alone distinguishes 10 (ten) different meanings.

**Comment by alxlo** [comment]
At least add "Design construct that provides an abstraction of the behavior of concrete components, declares possible interactions with these components and restrictions for such interactions."

**Comment by gernotstarke** [comment]
+1
