### ISSUE TITLE
discuss if "translation tables" are really needed

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/glossary#99]
maintaining these is a lot of effort and somewhat error-prone due to manual work...

One proposition: Just remove them completely to keep the glossary EN-only.

maybe have another artifact within iSAQB providing translations

**Comment by alxlo** [comment]
As long as we only have an EN version, many of my students where glad to have the translation available.

**Comment by gernotstarke** [comment]
ich hab's fast befürchtet, dass jemand sich dafür interessiert... warum sollte irgendwas EINFACHER werden?
Hast DU nicht gerade über KISS geschrieben??

**Comment by mikesperber** [comment]
Ich bin auf @alxlo seiner Seite. (Und @gernotstarke - Du meinst LEICHTER, nicht EINFACHER :-) ) Helfe gerne.

**Comment by ulibecker** [comment]
Agree with @alxlo. It also happens regularly in my german trainings that participants ask for the english terms, and I am happy I can refer them to the glossary :smile:

**Comment by gernotstarke** [comment]
Decision: Keep those.
